### ISSUE TITLE
Add data store for server specific settings

### ISSUE THREAD

**Issue by BrandonClapp** [BrandonClapp/babble#8]
A data store for the server would be nice for persisting data through server restarts, such as...
- Channels
- Users
- User permissions

**Comment by toannguyen83** [comment]
Let's do it ini file :D
Tom has fork of ini repo

**Comment by toannguyen83** [comment]
https://github.com/BrandonClapp/babble/commit/54b7483d5286037d1a761a2e9dbc8407393349e1
- Added sqlite persistent store 
- Added Channels CRUD

**Comment by toannguyen83** [comment]
https://github.com/BrandonClapp/babble/commit/e4b6590be424fb84ed1bd942f554a96e24285538
- Added user dal

https://github.com/BrandonClapp/babble/commit/e4b6590be424fb84ed1bd942f554a96e24285538
- Working concept of stored password and salt

**Comment by toannguyen83** [comment]
I think datastore is in good shape with sqlite for now, closing.
